In [3]:
import numpy as np

In [8]:
filename = './presidential_polls.csv'
data_arr = np.loadtxt(filename,
                     delimiter = ',',
                     skiprows=1,
                     dtype = str,
                     usecols=(3,17,18,19),
                     )
print(data_arr)
print(type(data_arr))

[['"Clinton vs. Trump vs. Johnson"' '42.6414' '40.86509' '5.675099']
 ['"Clinton vs. Trump vs. Johnson"' '43.29659' '44.72984' '3.401513']
 ['"Clinton vs. Trump vs. Johnson"' '46.29779' '40.72604' '6.401513']
 ...
 ['"Clinton vs. Trump vs. Johnson"' '45.9713' '39.97518' '']
 ['"Clinton vs. Trump vs. Johnson"' '45.2939' '46.66175' '1.596946']
 ['"Clinton vs. Trump vs. Johnson"' '31.62721' '44.65947' '']]
<class 'numpy.ndarray'>


In [11]:
print(data_arr.ndim)
print(data_arr.shape)
print(data_arr.dtype)

2
(10236, 4)
<U31


In [12]:
import random

In [22]:
arr = np.random.rand(4,4)
print(arr)

[[0.36140501 0.04486579 0.37037336 0.8599229 ]
 [0.76606248 0.46548819 0.14555643 0.37804611]
 [0.50837378 0.65651332 0.09863506 0.03019332]
 [0.23441883 0.29054317 0.51848432 0.690925  ]]


In [26]:
arr = np.random.randint(-1,5,size=(3,4))
print(arr)
print(type(arr))
print(arr.dtype)

[[ 2  3  4  0]
 [ 3  3  0  1]
 [-1  0  3 -1]]
<class 'numpy.ndarray'>
int64


In [27]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
